schema: schema.graphql
extensions:
  endpoints:
    One:
      url: https://b2p7dsy7qvaajbeuaqwjgotce4.appsync-api.eu-central-1.amazonaws.com/graphql
      headers:
        X-Api-Key: da2-dh6dys6oxbdbnb3teiibo6v5tu
