schema: schema.graphql
extensions:
  endpoints:
    One:
      url: https://q7rearab2ncc3goc6fxao5owgm.appsync-api.eu-central-1.amazonaws.com/graphql
      headers:
        X-Api-Key: da2-mggi3hokrvatdeijdpy5ohqtym
