projects:
  Codegen Project:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
      - src/API.ts
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/API.ts
        docsFilePath: src/graphql
        region: eu-central-1
        apiId: vv5h5sdbl5huxgmwjerlpufl4y
        frontend: javascript
        framework: react
        maxDepth: 2
extensions:
  amplify:
    version: 3
